In [451]:
import numpy as np
import pandas as pd

In [452]:
books = pd.read_csv("D:\\Users\\Public\\Public Documents\\Datasets\\Book Recommender System\\Books.csv")
ratings = pd.read_csv("D:\\Users\\Public\\Public Documents\\Datasets\\Book Recommender System\\Ratings.csv")
users = pd.read_csv("D:\\Users\\Public\\Public Documents\\Datasets\\Book Recommender System\\Users.csv")

C:\Users\Vishal\AppData\Local\Temp\ipykernel_13108\625923699.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("D:\\Users\\Public\\Public Documents\\Datasets\\Book Recommender System\\Books.csv")

In [453]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [454]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [455]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [456]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [457]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [458]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [459]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [460]:
books.duplicated().sum()

0

In [461]:
ratings.duplicated().sum()

0

In [462]:
users.duplicated().sum()

0

### Popularity Bases Recommender System

In [463]:
ratings_with_name = ratings.merge(books, on="ISBN")

In [464]:
num_rating_df = ratings_with_name.groupby("Book-Title").count()["Book-Rating"].reset_index()

num_rating_df.rename(columns={"Book-Rating":"num_ratings"}, inplace=True)

num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [465]:
avg_rating_df = ratings_with_name.groupby("Book-Title").mean()["Book-Rating"].reset_index()

avg_rating_df.rename(columns={"Book-Rating":"avg_ratings"}, inplace=True)

avg_rating_df

                                               Book-Title  avg_ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [466]:
popular_df = num_rating_df.merge(avg_rating_df, on="Book-Title")

popular_df

,Book-Title,num_ratings,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [467]:
popular_df = popular_df[popular_df["num_ratings"]>=250].sort_values("avg_ratings", ascending=False).head(50)

popular_df

,Book-Title,num_ratings,avg_ratings
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569
111073,Lord of the Flies,259,3.818533
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472

In [468]:
popular_df1 = popular_df.merge(books, on="Book-Title").drop_duplicates("Book-Title")[["Book-Title", "Book-Author", "Image-URL-M", "num_ratings", "avg_ratings"]]

In [469]:
popular_df1

,Book-Title,Book-Author,Image-URL-M,num_ratings,avg_ratings
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
47,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
53,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
55,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
62,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
63,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
72,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
73,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
78,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
88,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,268,4.328358
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,335,4.289552
100,Into the Wild,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...,252,4.273810
103,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
116,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
117,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,283,4.173145
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,275,4.098182
126,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
130,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,389,4.087404
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,265,4.086792
135,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,279,4.075269
137,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,321,4.037383
140,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,302,4.006623
141,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,322,4.006211
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,318,4.003145
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,336,4.000000
157,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,314,3.964968
163,Silence of the Lambs,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,256,3.960938
166,About a Boy,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...,262,3.900763
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,278,3.888489
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,266,3.875940
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,269,3.825279
182,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
186,Lord of the Flies,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...,259,3.818533
192,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,413,3.796610
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,301,3.777409
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,356,3.772472

### Collaborative Filter based Recommender System

In [470]:
x = ratings_with_name.groupby("User-ID").count()["Book-Rating"] > 200
users_200 = x[x].index

In [471]:
filtered_rating = ratings_with_name[ratings_with_name["User-ID"].isin(users_200)]

In [472]:
users_200.shape         # this many users gave ratings more than 200 each

(811,)

In [473]:
# so we have done filtering on the basis of users now let us look at books


## for users we have chosen those users who had given more than 200 ratings

In [474]:
y = filtered_rating.groupby("Book-Title").count()["Book-Rating"]>50
famous_books = y[y].index

In [475]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [476]:
pt = final_ratings.pivot_table(index="Book-Title", columns="User-ID", values="Book-Rating")
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [477]:
pt.fillna(0, inplace=True)

In [478]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [479]:
from sklearn.metrics.pairwise import cosine_similarity

In [480]:
similarity_scores = cosine_similarity(pt) 

# finding euclideon distance for every book vector

In [481]:
# for finding the index of any book

np.where(pt.index=="Zoya")[0][0]

677

In [482]:
sorted(list(enumerate(similarity_scores[0])), key=lambda x:x[1], reverse=True)[1:6]

# enumerate: distance ke sath-sath item ka index bhi dikh jayega

[(46, 0.2702651417103732),
 (524, 0.2639619371123497),
 (80, 0.23669374347400993),
 (610, 0.23299389358170394),
 (530, 0.2262639743141286)]

In [483]:
def recommend_books(book_name):
    # fetch book index
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])), key=lambda x:x[1], reverse=True)[1:6]
    
    for i in similar_items:
        print(pt.index[i[0]])

In [484]:
def recommend_books2(book_name):
    # fetch book index
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])), key=lambda x:x[1], reverse=True)[1:6]
    
    data=[]
    for i in similar_items:
        item = []
        
        # list ko append karne se 2D list ban jata hai, that's why extend
        temp_df = books[books["Book-Title"]==pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates("Book-Title")["Book-Title"].values))
        item.extend(list(temp_df.drop_duplicates("Book-Title")["Book-Author"].values))
        item.extend(list(temp_df.drop_duplicates("Book-Title")["Image-URL-M"].values))
        
        data.append(item)
    
    return data

In [485]:
recommend_books2("1984")

[['Animal Farm',
  'George Orwell',
  'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'],
 ["The Handmaid's Tale",
  'Margaret Atwood',
  'http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg'],
 ['Brave New World',
  'Aldous Huxley',
  'http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg'],
 ['The Vampire Lestat (Vampire Chronicles, Book II)',
  'ANNE RICE',
  'http://images.amazon.com/images/P/0345313860.01.MZZZZZZZ.jpg'],
 ['The Hours : A Novel',
  'Michael Cunningham',
  'http://images.amazon.com/images/P/0312243022.01.MZZZZZZZ.jpg']]

In [486]:
books["Image-URL-L"][0]

'http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg'

In [491]:
import pickle
#pickle.dump(popular_df1, open("popular.pkl", "wb"))

In [490]:
#pickle.dump(pt, open("pt.pkl", "wb"))
#pickle.dump(books, open("books.pkl", "wb"))
#pickle.dump(similarity_scores, open("similarity_scores.pkl", "wb"))

In [488]:
count=0
for i in popular_df1["Book-Title"]:
    count+=1
    print(i[:50], count)

Harry Potter and the Prisoner of Azkaban (Book 3) 1
Harry Potter and the Goblet of Fire (Book 4) 2
Harry Potter and the Sorcerer's Stone (Book 1) 3
Harry Potter and the Order of the Phoenix (Book 5) 4
Harry Potter and the Chamber of Secrets (Book 2) 5
The Hobbit : The Enchanting Prelude to The Lord of 6
The Fellowship of the Ring (The Lord of the Rings, 7
Harry Potter and the Sorcerer's Stone (Harry Potte 8
The Two Towers (The Lord of the Rings, Part 2) 9
To Kill a Mockingbird 10
The Da Vinci Code 11
The Five People You Meet in Heaven 12
The Catcher in the Rye 13
The Lovely Bones: A Novel 14
1984 15
Prodigal Summer: A Novel 16
Neverwhere 17
The Secret Life of Bees 18
Stupid White Men ...and Other Sorry Excuses for th 19
Tuesdays with Morrie: An Old Man, a Young Man, and 20
The Red Tent (Bestselling Backlist) 21
The Hitchhiker's Guide to the Galaxy 22
Nickel and Dimed: On (Not) Getting By in America 23
Into the Wild 24
Fahrenheit 451 25
Girl with a Pearl Earring 26
Outlander 27
Where the Heart Is (Oprah's Book Club (Paperback)) 28
Seabiscuit: An American Legend 29
Life of Pi 30
The Bean Trees 31
A Child Called \It\": One Child's Courage to Survi 32
ANGELA'S ASHES 33
Good in Bed 34
Fast Food Nation: The Dark Side of the All-America 35
American Gods 36
Skipping Christmas 37
Left Behind: A Novel of the Earth's Last Days (Lef 38
The Golden Compass (His Dark Materials, Book 1) 39
The Color Purple 40
Silence of the Lambs 41
About a Boy 42
Seven Up (A Stephanie Plum Novel) 43
The Alchemist: A Fable About Following Your Dream 44
Hard Eight : A Stephanie Plum Novel (A Stephanie P 45
Suzanne's Diary for Nicholas 46
Lord of the Flies 47
A Prayer for Owen Meany 48
The Vampire Lestat (Vampire Chronicles, Book II) 49
White Oleander : A Novel (Oprah's Book Club) 50

In [489]:
count=0
for i in popular_df1["Image-URL-M"]:
    count+=1
    print(i[:50], count)

http://images.amazon.com/images/P/0439136350.01.MZ 1
http://images.amazon.com/images/P/0439139597.01.MZ 2
http://images.amazon.com/images/P/0590353403.01.MZ 3
http://images.amazon.com/images/P/043935806X.01.MZ 4
http://images.amazon.com/images/P/0439064872.01.MZ 5
http://images.amazon.com/images/P/0345339681.01.MZ 6
http://images.amazon.com/images/P/0345339703.01.MZ 7
http://images.amazon.com/images/P/059035342X.01.MZ 8
http://images.amazon.com/images/P/0345339711.01.MZ 9
http://images.amazon.com/images/P/0446310786.01.MZ 10
http://images.amazon.com/images/P/0385504209.01.MZ 11
http://images.amazon.com/images/P/0786868716.01.MZ 12
http://images.amazon.com/images/P/0316769487.01.MZ 13
http://images.amazon.com/images/P/0316666343.01.MZ 14
http://images.amazon.com/images/P/0451524934.01.MZ 15
http://images.amazon.com/images/P/0060959037.01.MZ 16
http://images.amazon.com/images/P/0380789019.01.MZ 17
http://images.amazon.com/images/P/0142001740.01.MZ 18
http://images.amazon.com/images/P/0060392452.01.MZ 19
http://images.amazon.com/images/P/0385484518.01.MZ 20
http://images.amazon.com/images/P/0312195516.01.MZ 21
http://images.amazon.com/images/P/0671461494.01.MZ 22
http://images.amazon.com/images/P/0805063897.01.MZ 23
http://images.amazon.com/images/P/0385486804.01.MZ 24
http://images.amazon.com/images/P/3257208626.01.MZ 25
http://images.amazon.com/images/P/0452282152.01.MZ 26
http://images.amazon.com/images/P/0440222915.01.MZ 27
http://images.amazon.com/images/P/0446672211.01.MZ 28
http://images.amazon.com/images/P/0449005615.01.MZ 29
http://images.amazon.com/images/P/0151008116.01.MZ 30
http://images.amazon.com/images/P/0060915544.01.MZ 31
http://images.amazon.com/images/P/1558743669.01.MZ 32
http://images.amazon.com/images/P/0684874350.01.MZ 33
http://images.amazon.com/images/P/0743418174.01.MZ 34
http://images.amazon.com/images/P/0060938455.01.MZ 35
http://images.amazon.com/images/P/0380789035.01.MZ 36
http://images.amazon.com/images/P/0385505833.01.MZ 37
http://images.amazon.com/images/P/0842329129.01.MZ 38
http://images.amazon.com/images/P/037582345X.01.MZ 39
http://images.amazon.com/images/P/0671617028.01.MZ 40
http://images.amazon.com/images/P/0312924585.01.MZ 41
http://images.amazon.com/images/P/1573227331.01.MZ 42
http://images.amazon.com/images/P/0312265840.01.MZ 43
http://images.amazon.com/images/P/0062502174.01.MZ 44
http://images.amazon.com/images/P/0312983867.01.MZ 45
http://images.amazon.com/images/P/0316969443.01.MZ 46
http://images.amazon.com/images/P/0399501487.01.MZ 47
http://images.amazon.com/images/P/0345361792.01.MZ 48
http://images.amazon.com/images/P/0345313860.01.MZ 49
http://images.amazon.com/images/P/0316284955.01.MZ 50